### PR TITLE
Initial doc for check & resource creation flow of events

### PR DESCRIPTION
**Pull request by jjbuchan**
Shows the process of events from creation of a resource via the API to checks being sent down to the relevant envoys.

Changes will be needed.

### CODE REVIEW

**Comment by itzg** [comment]
FYI I try to give my draw.io diagrams a suffix of ".drawio.png" to denote that it is editable.

**Comment by jjbuchan** [comment]
Renamed

**Comment by itzg** [comment]
In check-creation-api, 3.2.2 of Step 4.5 (sounds like a legal doc reference :) ), corresponds nicely to the role that presence monitor could play in my comment https://one.rackspace.com/display/monitoring/Random+Salus+Thoughts?focusedCommentId=542679558#comment-542679558 under Disconnections

**Comment by jjbuchan** [comment]
> how the kafka message keys should be composed

Agreed.  I would have needed to do more kafka research/refresh to see that and as it's something we can figure out later I left it for now.

Going to merge this so any changes can be seen in new commits.

**Pull request merged**
