### PR TITLE
Added policy endpoints and cleaned things up

### PR DESCRIPTION
**Pull request by jjbuchan**
First commit is the policy additions, then I deleted my local workspace, re-imported from that first commit, then the later commits are cleaning up everything a little - some removal of duplicates and some reorganizing of things.

### CODE REVIEW

**Comment by itzg** [comment]
There's a large amount of diffs here (and a conflict)...the net result might be fine, but is a little worrisome.

**Comment by itzg** [comment]
...what you might need to do is:
1. Export just your new entries into a temp yaml file
2. Wipe or create a new workspace
3. Import the laster master copy of workspace yaml
4. Import your temp/partial yaml workspace file
5. Export and push

**Comment by jjbuchan** [comment]
What you suggest sounds like the equivalent of what's in my first commit here?

I didn't notice the conflicts before and not sure why'd they'd be there, but will take a look.

Since I was trying to clean up the whole file, i'm not sure if there's a way to avoid a difficult diff?

Once I fix conflicts the only real way to review might be for you to wipe your workspace and import this and see if anything looks off?

**Comment by jjbuchan** [comment]
I think if we all follow George's method of wiping our workspace everytime new changes are available, and also being careful about where we decide to create new folders/requests it should limit this kinda PR in future.

**Comment by itzg** [comment]
After the merge conflict, I'll just trust the net result. Even if anything got lost, can always dip back into history to pick out the specific item. (And I can locally save off my workspace :) )

**Comment by jjbuchan** [comment]
Conflict fixed.

I thought I had done a `git pull` before starting this branch but it seems like I didn't or something went wrong... but since I started my reworking of the file by using the "Import from URL" option and using the raw master URL, I already had all of masters changes in here.

The re-ordering of some things led to the conflict.  Here is the only conflict.  I've verified each of those pieces is still in this file, they have just been separated.

```
<<<<<<< HEAD
=======
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: http://localhost:8089/api/tenant/aaaaaa/monitors/{% prompt 'Monitor ID',
      '', '', '', false %}
    _type: request
  - _id: req_872b76e7e3684e939adc64afd9ac0b4e
    authentication: {}
    body:
      mimeType: application/json
      text: >-
        {
          "resourceId": "{% prompt 'Resource ID', '', 'development:0', '', false, true %}",
          "details": {
            "type": "local",
            "plugin": {
              "type": "cpu"
            }
          }
        }
    created: 1566236692691
    description: ""
    headers:
      - id: pair_5e0b8bc427a545648bcb0fe4eb982a98
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1563231843254.5
    method: POST
    modified: 1566241926279
    name: Test local monitor given resource
    parameters: []
    parentId: fld_5f92cca3cbdf44189e1ee614d0036b0f
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: http://localhost:8089/api/tenant/{% prompt 'Tenant', '', '', 'tenantId',
      false, true %}/test-monitor
    _type: request
  - _id: fld_5f92cca3cbdf44189e1ee614d0036b0f
    created: 1566236728350
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1555360404480
    modified: 1566236741282
    name: Test-Monitor
    parentId: fld_2cd444041994485fa243cdab9f615271
>>>>>>> origin/master
```

**Comment by jjbuchan** [comment]
huh, thought i merged this already

**Pull request merged**
