### PR TITLE
Rename to zone watcher and bump modules

### PR DESCRIPTION
**Pull request by jjbuchan**
Zone Watcher doesn't appear to be pulled in by any other repo right now, which makes sense, so I think this PR and https://github.com/racker/salus-telemetry-zone-watcher/pull/4 are all that's needed.

### CODE REVIEW

**Comment by jjbuchan** [comment]
Hmm... a lot of conflicts here 👎 

I'll try again once the zone watcher pr is merged.

**Comment by itzg** [comment]
and https://github.com/racker/salus-telemetry-bundle/pull/51 is in flight

**Comment by jjbuchan** [comment]
I've removed everything except the zone service.  Will refresh it with master once all other prs are merged.

**Comment by jjbuchan** [comment]
Not sure why it kept saying the path I deleted was a conflict.  This should be good now.

**Pull request merged**
